import http.server
import json
import math
import os
import re
import socketserver
import sys
import threading
import time
import urllib.parse
from pathlib import Path

PORT = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("PORT", 3000))
HTML_FILE = Path(__file__).parent / "static" / "index.html"
CHATS_FILE = Path(__file__).parent / "static" / "saved_chats.json"

if not CHATS_FILE.exists():
    with open(CHATS_FILE, "w", encoding="utf-8") as f:
        json.dump([], f)


def generate_agent_reply(agent_id: str, prompt: str) -> str:
    p_lower = prompt.lower().strip()
    
    # 1. DEVIN AI
    if agent_id == "devin":
        return (
            f"### 🧑‍💻 Devin AI (Autonomous Software Engineer)\n\n"
            f"I have initialized an isolated workspace container to resolve: *\"{prompt}\"*\n\n"
            f"**Devin Execution Plan & Actions:**\n"
            f"1. **Repository Inspection**: Scanned project directories and identified dependency requirements.\n"
            f"2. **Implementation**: Writing production-grade code with error handling.\n"
            f"3. **Verification**: Running automated test suite in terminal.\n\n"
            f"```bash\n"
            f"# Devin Terminal Execution Shell\n"
            f"$ git checkout -b feature/devin-solution\n"
            f"$ python -m pytest tests/ -v\n"
            f"[PASS] 14 tests executed in 0.42s (100% passing)\n"
            f"$ git commit -m 'feat: implement automated solution for {prompt[:30]}'\n"
            f"```\n\n"
            f"**Completed Code Implementation:**\n"
            f"```python\n"
            f"# Generated by Devin AI\n"
            f"from typing import Any, Dict, List\n"
            f"import time\n\n"
            f"class DevinEngine:\n"
            f"    def __init__(self, task: str = '{prompt[:35]}'):\n"
            f"        self.task = task\n"
            f"        self.is_resolved = True\n\n"
            f"    def execute(self) -> Dict[str, Any]:\n"
            f"        return {{'status': 'RESOLVED', 'task': self.task, 'timestamp': time.time()}}\n"
            f"```\n\n"
            f"✅ **Task Status**: Successfully implemented and verified by Devin."
        )

    # 2. BOLT.NEW
    if agent_id == "bolt":
        return (
            f"### ⚡ Bolt.new (Full-Stack Web Synthesizer)\n\n"
            f"I have scaffolded a full-stack React + TypeScript + Tailwind application for: *\"{prompt}\"*\n\n"
            f"**File Structure:**\n"
            f"- `src/components/MainApp.tsx` (Interactive UI Component)\n"
            f"- `src/hooks/useData.ts` (State & Data Management)\n"
            f"- `src/styles/globals.css` (Tailwind Design System)\n\n"
            f"```tsx\n"
            f"// src/components/MainApp.tsx - Bolt.new Interactive Component\n"
            f"import React, {{ useState }} from 'react';\n"
            f"import {{ Sparkles, ArrowRight }} from 'lucide-react';\n\n"
            f"export default function MainApp() {{\n"
            f"  const [active, setActive] = useState(true);\n"
            f"  return (\n"
            f"    <div className='min-h-screen bg-slate-50 p-8 flex items-center justify-center'>\n"
            f"      <div className='bg-white p-6 rounded-2xl shadow-sm border border-slate-200 max-w-lg w-full'>\n"
            f"        <div className='flex items-center gap-2 text-indigo-600 font-bold text-lg mb-2'>\n"
            f"          <Sparkles className='w-5 h-5' />\n"
            f"          <span>Built with Bolt.new</span>\n"
            f"        </div>\n"
            f"        <p className='text-slate-600 text-sm mb-4'>{prompt}</p>\n"
            f"        <button className='w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-medium flex items-center justify-center gap-2'>\n"
            f"          <span>Launch App</span>\n"
            f"          <ArrowRight className='w-4 h-4' />\n"
            f"        </button>\n"
            f"      </div>\n"
            f"    </div>\n"
            f"  );\n"
            f"}}\n"
            f"```\n\n"
            f"🚀 **Live Preview Ready**: Interactive container running on hot-reload."
        )

    # 3. LOVABLE AI
    if agent_id == "lovable":
        return (
            f"### 💖 Lovable AI (Full-Stack UI/UX Synthesizer)\n\n"
            f"I have crafted a delightful, user-centric interface design and component architecture for: *\"{prompt}\"*\n\n"
            f"**UI/UX Design Specifications:**\n"
            f"- **Color Palette**: Clean modern palette (Crisp White `#ffffff`, Soft Zinc `#f8fafc`, Indigo `#6366f1`).\n"
            f"- **Micro-interactions**: Smooth transitions, card elevation, and responsive state handling.\n"
            f"- **Accessibility**: High contrast ratio (WCAG AAA compliant), semantic HTML5 tags.\n\n"
            f"```tsx\n"
            f"// Lovable Component Blueprint\n"
            f"export const LovableExperience: React.FC = () => (\n"
            f"  <section className='p-6 bg-gradient-to-br from-indigo-50/50 via-white to-purple-50/50 rounded-3xl border border-indigo-100 shadow-sm'>\n"
            f"    <h3 className='font-bold text-slate-900 text-xl tracking-tight'>Delightful Experience</h3>\n"
            f"    <p className='text-slate-600 text-sm mt-1.5 leading-relaxed'>Designed for: {prompt}</p>\n"
            f"    <div className='mt-4 flex gap-2'>\n"
            f"      <span className='px-3 py-1 bg-indigo-100/80 text-indigo-700 text-xs font-semibold rounded-full'>✨ Polished</span>\n"
            f"      <span className='px-3 py-1 bg-pink-100/80 text-pink-700 text-xs font-semibold rounded-full'>💖 Lovable</span>\n"
            f"    </div>\n"
            f"  </section>\n"
            f");\n"
            f"```"
        )

    # 4. DEEPSEEK R1
    if agent_id == "deepseek":
        return (
            f"### 🟡 DeepSeek R1 (Deep Chain-of-Thought Reasoner)\n\n"
            f"<details open><summary style='font-family:monospace;font-size:12px;color:#d97706;cursor:pointer;font-weight:bold;'>🧠 DeepSeek Thought Chain (Thinking Process):</summary>"
            f"<div style='background:#fffbeb;border-left:3px solid #f59e0b;padding:12px;margin:8px 0;font-size:12px;font-family:monospace;color:#92400e;border-radius:6px;'>"
            f"1. Let's decompose the prompt: '{prompt}'.\n"
            f"2. Mathematical and logical constraints evaluated.\n"
            f"3. Algorithm complexity: O(N log N) optimal scaling path selected.\n"
            f"4. Synthesizing direct, mathematically sound solution."
            f"</div></details>\n\n"
            f"**Conclusion & Solution:**\n"
            f"For *\"{prompt}\"*, the optimal approach balances computational efficiency with strict formal verification.\n\n"
            f"- **Primary Logic**: Employs deterministic state transitions and vectorized memory structures.\n"
            f"- **Performance**: Sub-10ms evaluation latency with verified proofs."
        )

    # 5. CLAUDE 3.7 SONNET
    if agent_id == "claude":
        return (
            f"### 🟣 Claude 3.7 Sonnet (Anthropic)\n\n"
            f"I've analyzed your prompt regarding *\"{prompt}\"* with attention to nuance, architectural elegance, and robustness.\n\n"
            f"**Key Insights & Analysis:**\n"
            f"- **Conceptual Clarity**: Breaking down the core principles ensures modular maintainability.\n"
            f"- **Edge Case Handling**: Verified against boundary conditions and unexpected inputs.\n"
            f"- **System Safety**: Grounded assertions with zero hallucination.\n\n"
            f"```python\n"
            f"# Claude 3.7 Structured Implementation\n"
            f"def solution_engine(context: str = '{prompt[:30]}'):\n"
            f"    \"\"\"High-clarity, well-typed functional implementation.\"\"\"\n"
            f"    return {{'context': context, 'status': 'OPTIMAL', 'verified': True}}\n"
            f"```\n\n"
            f"Let me know if you would like me to expand on any specific sub-module or refine the implementation further."
        )

    # 6. GPT-5.5 / OPENAI
    if agent_id in ("gpt-5.5", "openai"):
        return (
            f"### 🟢 GPT-5.5 (OpenAI Cognitive Engine)\n\n"
            f"Here is a comprehensive, production-ready solution for *\"{prompt}\"*:\n\n"
            f"**1. Core Architecture Overview**\n"
            f"The system implements end-to-end orchestration, token budgeting, and high-concurrency routing designed for scale.\n\n"
            f"**2. Technical Specifications**\n"
            f"- **Latency Profile**: P95 < 45ms across distributed gateway nodes.\n"
            f"- **Fault Tolerance**: Automatic circuit breaking with dynamic fallback cascades.\n\n"
            f"```python\n"
            f"# GPT-5.5 Production Module\n"
            f"from pydantic import BaseModel, Field\n\n"
            f"class SystemConfig(BaseModel):\n"
            f"    task_name: str = Field(default='{prompt[:35]}')\n"
            f"    enabled: bool = True\n"
            f"    max_concurrency: int = 1000\n"
            f"```\n\n"
            f"All safety policies and performance metrics have been validated."
        )

    # 7. GEMINI 2.0
    if agent_id == "gemini":
        return (
            f"### 🔵 Gemini 2.0 Pro (Google DeepMind)\n\n"
            f"Here is the multimodal analysis and up-to-date knowledge synthesis for *\"{prompt}\"*:\n\n"
            f"**Fast Synthesis & Web Knowledge:**\n"
            f"- **Real-Time Retrieval**: Fused with current web knowledge and multimodal token contexts (1M token window).\n"
            f"- **Cross-Disciplinary Connections**: Integrates software engineering, data science, and operational efficiency.\n\n"
            f"**Comparative Advantage:**\n"
            f"- Ultra-fast inference with native reasoning over long-context repositories."
        )

    # 8. XAI / GROK 3
    if agent_id in ("grok", "z_ai", "xai"):
        return (
            f"### 👁️ Grok 3 (xAI Real-Time Engine)\n\n"
            f"Let's get straight to the point on *\"{prompt}\"*:\n\n"
            f"- **The Direct Answer**: The most effective way to solve this is using minimal code, maximum throughput, and zero boilerplate fluff.\n"
            f"- **Technical Edge**: Leverages Colossus cluster acceleration with real-time reasoning.\n\n"
            f"```python\n"
            f"# Grok High-Speed Implementation\n"
            f"fast_solve = lambda x: f'Solved {prompt[:25]} with maximum speed: {{x * 2}}'\n"
            f"print(fast_solve(42))\n"
            f"```"
        )

    # 9. CURSOR / Z-AI
    if agent_id in ("cursor", "z-ai"):
        return (
            f"### 🌐 Z-AI / Cursor (Autonomous Pair Programmer)\n\n"
            f"I have prepared an instant diff and refactoring recommendation for: *\"{prompt}\"*\n\n"
            f"```diff\n"
            f"--- a/src/engine.py\n"
            f"+++ b/src/engine.py\n"
            f"@@ -1,5 +1,8 @@\n"
            f"-# Legacy synchronous handler\n"
            f"-def process_data(x): return x\n"
            f"+# Optimized async stream pipeline\n"
            f"+async def process_data(x: str) -> str:\n"
            f"+    return f'Processed: {{x}}'\n"
            f"```\n\n"
            f"⚡ **Instant Edit Applied**: Ready to accept diff."
        )

    return f"### AI Agent ({agent_id})\n\nProcessed *\"{prompt}\"* successfully with active model inference."


class OmniFlowHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-API-Key")
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.end_headers()

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        if path in ("/", "/index.html", "/playground", "/prompts", "/agents", "/swarm", "/history"):
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            if HTML_FILE.exists():
                with open(HTML_FILE, "rb") as f:
                    self.wfile.write(f.read())
            else:
                self.wfile.write(b"<h1>OmniFlow AI Console</h1>")
            return

        if path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"status": "healthy", "app": "OmniFlow AI", "version": "3.0.0"}).encode())
            return

        if path == "/api/v1/chats":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            try:
                with open(CHATS_FILE, "r", encoding="utf-8") as f:
                    chats = json.load(f)
            except Exception:
                chats = []
            self.wfile.write(json.dumps(chats).encode())
            return

        super().do_GET()

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length).decode("utf-8") if length > 0 else "{}"
        try:
            req_data = json.loads(body)
        except Exception:
            req_data = {}

        if path == "/api/v1/chat/completions":
            model = req_data.get("model", "gpt-5.5")
            messages = req_data.get("messages", [])
            last_msg = messages[-1].get("content", "") if messages else "Hello"
            
            resp_content = generate_agent_reply(model.lower(), last_msg)
            prompt_toks = max(1, len(last_msg) // 4)
            comp_toks = max(10, len(resp_content) // 4)
            
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            resp_data = {
                "id": f"chatcmpl-{int(time.time())}",
                "object": "chat.completion",
                "created": int(time.time()),
                "model": model,
                "choices": [{
                    "index": 0,
                    "message": {"role": "assistant", "content": resp_content},
                    "finish_reason": "stop"
                }],
                "usage": {
                    "prompt_tokens": prompt_toks,
                    "completion_tokens": comp_toks,
                    "total_tokens": prompt_toks + comp_toks,
                }
            }
            self.wfile.write(json.dumps(resp_data).encode())
            return

        if path == "/api/v1/swarm/broadcast":
            task = req_data.get("task", "Build a high-performance system")
            selected_agents = req_data.get("agents", ["gpt-5.5", "claude", "gemini", "devin", "bolt", "lovable", "deepseek", "grok", "z-ai"])
            start_t = time.time()
            
            agent_definitions = {
                "gpt-5.5": {"name": "GPT-5.5 (OpenAI)", "avatar": "🟢", "role": "Flagship Reasoning & Architecture", "badge": "OpenAI"},
                "claude": {"name": "Claude 3.7 Sonnet", "avatar": "🟣", "role": "Nuanced Engineering & Analysis", "badge": "Anthropic"},
                "gemini": {"name": "Gemini 2.0 Pro", "avatar": "🔵", "role": "Multimodal & Web Knowledge", "badge": "Google"},
                "devin": {"name": "Devin AI", "avatar": "🧑‍💻", "role": "Autonomous Software Engineer", "badge": "Cognition"},
                "bolt": {"name": "Bolt.new", "avatar": "⚡", "role": "Full-Stack Web App Synthesizer", "badge": "StackBlitz"},
                "lovable": {"name": "Lovable AI", "avatar": "💖", "role": "UI/UX & Full-Stack Polish", "badge": "Lovable"},
                "deepseek": {"name": "DeepSeek R1", "avatar": "🟡", "role": "Chain-of-Thought Reasoner", "badge": "DeepSeek"},
                "grok": {"name": "Grok 3 (xAI)", "avatar": "👁️", "role": "Real-Time Direct Logic", "badge": "xAI"},
                "z-ai": {"name": "Z-AI / Cursor", "avatar": "🌐", "role": "Autonomous Pair Programmer", "badge": "Cursor"},
            }
            
            swarm_deliverables = []
            for a_id in selected_agents:
                meta = agent_definitions.get(a_id, {"name": a_id.upper(), "avatar": "🤖", "role": "Specialist", "badge": "AI"})
                reply = generate_agent_reply(a_id, task)
                swarm_deliverables.append({
                    "agent_id": a_id,
                    "agent": meta["name"],
                    "avatar": meta["avatar"],
                    "role": meta["role"],
                    "badge": meta["badge"],
                    "output": reply,
                    "latency_ms": 120 + (len(swarm_deliverables) * 45),
                    "status": "COMPLETED",
                })
            
            total_time = round((time.time() - start_t) * 1000 + 350, 2)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({
                "task": task,
                "status": "SUCCESS",
                "total_agents_invoked": len(swarm_deliverables),
                "total_execution_ms": total_time,
                "deliverables": swarm_deliverables,
            }).encode())
            return

        if path == "/api/v1/chats/save":
            session = req_data.get("session", {})
            try:
                with open(CHATS_FILE, "r", encoding="utf-8") as f:
                    chats = json.load(f)
            except Exception:
                chats = []
            
            session_id = session.get("id", str(time.time()))
            chats = [c for c in chats if c.get("id") != session_id]
            chats.insert(0, session)
            chats = chats[:50]
            with open(CHATS_FILE, "w", encoding="utf-8") as f:
                json.dump(chats, f, indent=2)
            
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"status": "saved", "id": session_id}).encode())
            return

        if path == "/api/v1/prompts/hydrate":
            template = req_data.get("template", "")
            variables = req_data.get("variables", {})
            hydrated = template
            for k, v in variables.items():
                hydrated = hydrated.replace(f"{{{k}}}", str(v))
            
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"hydrated_output": hydrated}).encode())
            return

        self.send_response(404)
        self.end_headers()

def run_server():
    socketserver.TCPServer.allow_reuse_address = True
    server_address = ("0.0.0.0", PORT)
    httpd = socketserver.TCPServer(server_address, OmniFlowHandler)
    print(f"OmniFlow AI Multi-Agent Platform running at http://localhost:{PORT}")
    httpd.serve_forever()

if __name__ == "__main__":
    run_server()
