FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
RUN pip install --no-cache-dir .

COPY backend/app ./app
CMD ["celery", "-A", "app.services.worker_service", "worker", "--loglevel=info", "-c", "4"]
