name: Security Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Security Vulnerability Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
